import { Box, Typography } from "@mui/material";
import React from "react";
import { useThemeContext } from "../contexts/ThemeContext";

export default function TermAndCondition() {
  const { theme } = useThemeContext();

  return (
    <Box
      sx={{
        height: "100vh",
        pt: { xs: 6, md: 12 },
        background: theme && theme,
        display: "flex",
        // justifyContent: "center",
        alignItems: "center",
        flexDirection: "column",
        overflowY: "auto",
      }}
    >
      <Typography
        sx={{
          fontSize: { xs: "x-large", md: "3.2rem", sm:"30px",xs:"20px"},
          color: theme == "white" ? "gray" : "gray",
          marginTop:{sm:"50px",xs:"50px"},
          fontWeight: "bold",
          my: 2,
          py: { xs: 2, md: 8 },
        }}
      >
        TERMS OF USE
      </Typography>
      <Box
        sx={{
          width: "100%",
          height: "100%",
        }}
      >
        <Typography
          sx={{
            fontSize: { xs: "medium", md: "1.4rem" },
            color: theme == "white" ? "black" : "white",
            fontWeight: "bold",
            textAlign: "center",
            px: { xs: "5%", md: "5%" },
          }}
        >
            MetaSimba LLC (doing business as “Snow Leopard Society”) celebrates representation,
            inclusivity, and equal opportunities for all, through its community, web3 initiatives and collections
            of non-fungible tokens (“NFT”) based on the Ethereum blockchain to which are attached visual
            assets representing unique, full body artwork (“Snow Leopard Society NFT”).

            THESE TERMS AND CONDITIONS (“TERMS”) RULE THE RELATIONSHIP BETWEEN
            SNOW LEOPARD SOCIETY AND ANY PERSON (“USER”, “YOU”) ACCESSING AND/OR
            USING SNOW LEOPARD SOCIETYS’ WEBSITE (WWW.SNOWLEOPARDSOCIETY.IO,
            WWW.SLSNFT.IO, ALSO REFERRED TO HEREIN AS “SNOW LEOPARD SOCIETY
            WEBSITE”).

            <br/>
            <br/>
            PLEASE READ THESE TERMS CAREFULLY BEFORE USING THE SNOW LEOPARD
            SOCIETY WEBSITE.
          </Typography>


        <Typography
        sx={{
            fontSize: { xs: "medium", md: "1.4rem" },
            color: theme == "white" ? "black" : "white",
            fontWeight: "bold",
            textAlign: "center",
            px: { xs: "5%", md: "5%" },
        }}
        >

        <h1 sx={{
            fontSize: { xs: "medium", md: "1.4rem" },
            color: theme == "white" ? "black" : "white",
            fontWeight: "bold",
            textAlign: "center",
            }}>
        1. CONDITIONS OF USE OF THE SNOW LEOPARD SOCIETY WEBSITE
        </h1>

        THE SNOW LEOPARD SOCIETY WEBSITE IS INTENDED TO USERS WHO ARE AT LEAST
        EIGHTEEN (18) YEARS OLD. THUS, BY USING THE SNOW LEOPARD SOCIETY WEBSITE,
        YOU CONFIRM THAT YOU ARE AT LEAST EIGHTEEN (18) YEARS OLD AND YOU ARE
        DEEMED TO HAVE READ AND ACCEPTED THESE TERMS EXHAUSTIVELY AND
        UNCONDITIONALLY.

        IF THE USER IS UNDER EIGHTEEN (18) YEARS OLD, THE USER UNDERTAKES TO
        OBTAIN THE PRIOR AND EXPRESS CONSENT OF HIS/HER PARENT OR LEGAL
        GUARDIAN TO USE THE SNOW LEOPARD SOCIETY WEBSITE AND TO REVIEW THE
        TERMS WITH THEM. THE PARENT OR LEGAL GUARDIAN OF A USER UNDER EIGHTEEN
        (18) YEARS OLD UNDERTAKES TO ABIDE BY THESE TERMS AND ACKNOWLEDGES TO
        BE RESPONSIBLE FOR THE ACTIVITIES OF THE USER ON THE SNOW LEOPARD
        SOCIETY WEBSITE.

        IN CASE OF YOUR DISAGREEMENT, IN WHOLE OR IN PART, WITH THESE TERMS, YOU
        MUST IMMEDIATELY CEASE ANY AND ALL USE OF THE SNOW LEOPARD SOCIETY
        WEBSITE.

<h1 sx={{
      fontSize: { xs: "medium", md: "1.4rem" },
      color: theme == "white" ? "black" : "white",
      fontWeight: "bold",
      textAlign: "center",
    }}>
2. AMENDMENT TO THE TERMS
</h1>
THE TERMS MAY BE UPDATED FROM TIME TO TIME AS SNOW LEOPARD SOCIETY MAY
DEEM NECESSARY OR USEFUL.

IN THE EVENT YOU DO NOT AGREE TO THE TERMS, INCLUDING AS MAY BE AMENDED,
YOU SHALL CEASE ANY AND ALL UTILIZATION OF THE SNOW LEOPARD SOCIETY
WEBSITE AND RELATED SERVICES.

<h1 sx={{
      fontSize: { xs: "medium", md: "1.4rem" },
      color: theme == "white" ? "black" : "white",
      fontWeight: "bold",
      textAlign: "center",
    }}>
3. ACCESS TO THE SNOW LEOPARD SOCIETY WEBSITE
</h1>


YOU ARE PERSONALLY RESPONSIBLE FOR SETTING UP THE IT AND
TELECOMMUNICATIONS RESOURCES REQUIRED TO ACCESS THE SNOW LEOPARD
SOCIETY WEBSITE AND USE THE SERVICES. YOU SHALL BEAR THE COST OF
TELECOMMUNICATIONS WHEN ACCESSING THE INTERNET TO USE THE SNOW
LEOPARD SOCIETY WEBSITE.

SNOW LEOPARD SOCIETY RESERVES THE RIGHT TO, WITHOUT NOTICE NOR
COMPENSATION, TEMPORARILY OR PERMANENTLY, CLOSE THE SNOW LEOPARD
SOCIETY WEBSITE OR ACCESS TO ONE OR MORE SERVICES IN ORDER TO PERFORM
MAINTENANCE OPERATIONS. SNOW LEOPARD SOCIETY MAY CARRY OUT ANY
CHANGES AND IMPROVEMENTS TO THE SNOW LEOPARD SOCIETY WEBSITE AND
SERVICES THAT IT DEEMS NECESSARY.

<h1 sx={{
      fontSize: { xs: "medium", md: "1.4rem" },
      color: theme == "white" ? "black" : "white",
      fontWeight: "bold",
      textAlign: "center",
    }}>
4. SERVICES
</h1>

<h2 sx={{
      fontSize: { xs: "medium", md: "1.4rem" },
      color: theme == "white" ? "black" : "white",
      fontWeight: "bold",
      textAlign: "left",
    }}>
4.1 GENERAL SERVICES
</h2>

THE SNOW LEOPARD SOCIETY WEBSITE GIVES YOU ACCESS TO FUNCTIONALITIES,
FEATURES AND SERVICES RELATED TO SNOW LEOPARD SOCIETY NFT COLLECTIONS
AND COMMUNITY (THE “SERVICES”).

ACCESS TO SOME SERVICES MAY ONLY BE AVAILABLE TO THE HOLDER OF A SNOW
LEOPARD SOCIETY NFT AND REQUIRE PROOF OF OWNERSHIP BY CONNECTING A

SUPPORTED BLOCKCHAIN-BASED DIGITAL WALLET TO THE SNOW LEOPARD SOCIETY
WEBSITE (“DIGITAL WALLET”).

DIGITAL WALLETS ARE THIRD-PARTY PRODUCTS AND SERVICES THAT ARE NOT
AFFILIATED, IN ANY WAY WHATSOEVER, WITH SNOW LEOPARD SOCIETY NOR IN ITS
CUSTODY OR CONTROL. ACCESS AND USE OF DIGITAL WALLETS ARE AT THE USER’S
OWN RISK AND DISCRETION AND SUBJECT TO THEIR OWN APPLICABLE TERMS.

YOU ARE SOLELY RESPONSIBLE FOR YOUR DIGITAL WALLET SECURITY, INCLUDING
ASSOCIATED PASSWORDS, SEED WORDS, AND KEYS. SNOW LEOPARD SOCIETY
SHALL NOT, IN ANY EVENT WHATSOEVER, BE HELD RESPONSIBLE FOR ANY RISK
ASSOCIATED WITH YOUR ACCESS AND/OR USE OF A DIGITAL WALLET. IN THE EVENT
YOU LOSE OR CAN NO LONGER ACCESS YOUR DIGITAL WALLET, SNOW LEOPARD
SOCIETY CANNOT RETRIEVE YOUR SNOW LEOPARD SOCIETY NFT FROM YOUR
DIGITAL WALLET.

<h2 sx={{
      fontSize: { xs: "medium", md: "1.4rem" },
      color: theme == "white" ? "black" : "white",
      fontWeight: "bold",
      textAlign: "left",
    }}>
4.2 NFT PRIMARY SALE SERVICES ON THE SNOW LEOPARD SOCIETY WEBSITE
</h2>
THE SNOW LEOPARD SOCIETY WEBSITE MAY, IN ITS SOLE DISCRETION, GIVE YOU
ACCESS TO PRIMARY SALES OF SNOW LEOPARD SOCIETY NFTS THROUGH ONE OR
SEVERAL OF THE FOLLOWING ACCESS RIGHTS: WHITELIST AKA ALLOW LIST AND/OR
PUBLIC SALE.

YOU WILL BE REQUIRED TO CONNECT YOUR DIGITAL WALLET TO THE SNOW
LEOPARD SOCIETY WEBSITE IN ORDER TO, DEPENDING ON THE RIGHTS YOU HAVE
BEEN GRANTED ON THE PRIMARY SALE, (I) WHERE APPLICABLE, TRANSFER TO SNOW
LEOPARD SOCIETY THE APPLICABLE PURCHASE PRICE, AND (II) RECEIVE AN NFT.

APPLICABLE PURCHASE PRICE OF A SNOW LEOPARD SOCIETY ARE SET FORTH ON
THE SNOW LEOPARD SOCIETY WEBSITE AND ARE BINDING AT THE TIME OF
PURCHASE. ADDITIONAL FEES (INCLUDING GAS FEES) MAY BE REQUIRED AT THE
TIME OF PURCHASE TO COMPLETE THE SALE. SNOW LEOPARD SOCIETY DOES NOT
MONITOR NOR BENEFIT FROM THESE FEES.

SNOW LEOPARD SOCIETY WILL DIRECTLY TRANSFER THE SNOW LEOPARD SOCIETY
NFT YOU ACQUIRED TO THE SUPPORTED DIGITAL WALLET YOU CONNECTED TO THE
SNOW LEOPARD SOCIETY WEBSITE, DEPENDING THE CASE AND WHERE APPLICABLE,
UPON CONFIRMATION OF OWNERSHIP OF A SNOW LEOPARD SOCIETY NFT OR UPON
RECEIPT OF THE CORRESPONDING PURCHASE PRICE.

ALL SALES COMPLETED ON THE SNOW LEOPARD SOCIETY WEBSITE ARE FINAL.
PURSUANT TO APPLICABLE LAW, YOU ACKNOWLEDGE THAT NO WITHDRAWAL,
RETURN AND/OR REFUND RIGHTS APPLY.

<h2 sx={{
      fontSize: { xs: "medium", md: "1.4rem" },
      color: theme == "white" ? "black" : "white",
      fontWeight: "bold",
      textAlign: "left",
    }}>
4.3 NFT SECONDARY SALE ON THIRD-PARTY PLATFORM
</h2>
USER MAY RESELL AND/OR PURCHASE SNOW LEOPARD SOCIETY NFT ON THIRD-
PARTY PLATFORMS AS PART OF SECONDARY SALES.

PLATFORMS DEDICATED TO SECONDARY SALES ARE THIRD-PARTY SERVICES THAT
ARE NOT AFFILIATED WITH SNOW LEOPARD SOCIETY AND WHICH ACCESS AND USE
ARE AT USER’S OWN RISK AND DISCRETION AND SUBJECT TO THEIR OWN
APPLICABLE TERMS.

SNOW LEOPARD SOCIETY MAY BENEFIT FROM A PERCENTAGE OF THE RESALE
PRICE OF SNOW LEOPARD SOCIETY NFT, AS SET FORTH ON THE SNOW LEOPARD
SOCIETY WEBSITE AND SUBJECT TO THE THIRD-PARTY PLATFORM’S POLICY ON
WHICH THE RESALE IS COMPLETED.

YOU UNDERTAKE TO ONLY RESELL AND/OR PURCHASE SNOW LEOPARD SOCIETY
NFT ON THIRD-PARTY PLATFORMS THAT (I) CRYPTOGRAPHICALLY VERIFY EACH NFT
OWNER’S RIGHTS TO DISPLAY AND LIST A SNOW LEOPARD SOCIETY NFT FOR SALE,
TO ENSURE THAT ONLY THE ACTUAL OWNER OF THIS NFT CAN PROCEED WITH ITS
RESALE, AND (II) PROVIDE FOR A PERCENTAGE OF THE RESALE PRICE TO BE
AUTOMATICALLY GRANTED TO SNOW LEOPARDS SOCIETY
UPON RESALE.

BY RESELLING AND/OR PURCHASING A SNOW LEOPARD SOCIETY NFT ON AN
AUTHORIZED THIRD-PARTY PLATFORM, YOU AGREE TO ABIDE BY THESE TERMS.

<h1 sx={{
      fontSize: { xs: "medium", md: "1.4rem" },
      color: theme == "white" ? "black" : "white",
      fontWeight: "bold",
      textAlign: "center",
    }}>
5. UNDERTAKINGS OF THE PARTIES
</h1>

<h2 sx={{
      fontSize: { xs: "medium", md: "1.4rem" },
      color: theme == "white" ? "black" : "white",
      fontWeight: "bold",
      textAlign: "center",
    }}>
5.1 USERS UNDERTAKINGS
</h2>

USERS SHALL NOT, DIRECTLY OR INDIRECTLY, WITHOUT BEING EXPRESSLY
AUTHORIZED BY THESE TERMS AND/OR THE DIGITAL OWNERSHIP ASSIGNMENT, OR
BY PRIOR WRITTEN CONSENT OF SNOW LEOPARD SOCIETY, IN ANY WAY
WHATSOEVER:

(I) COPY, MODIFY, COMMUNICATE, TRANSMIT OR CREATE ANY DERIVATIVE WORK,
USE, COMMERCIALIZE OR REPRODUCE ALL OR PART OF THE SNOW LEOPARD
SOCIETY WEBSITE AND/OR SNOW LEOPARD SOCIETY PROPERTY, AND RELATED
INTELLECTUAL PROPERTY RIGHTS OF SNOW LEOPARD SOCIETY, OR REGISTER OR
ATTEMPT TO REGISTER ANY TRADEMARK OR COPYRIGHT OR OTHERWISE ACQUIRE
ADDITIONAL INTELLECTUAL PROPERTY RIGHTS IN OR TO ANY SNOW LEOPARD
SOCIETY PROPERTY; USE THE SNOW LEOPARD SOCIETY WEBSITE OR ANY SNOW
LEOPARD SOCIETY PROPERTY TO CREATE, ENDORSE, SUPPORT, PROMOTE OR
CONDONE ANY CONTENT, MATERIAL OR SPEECH THAT IS, OR MAY BE DEEMED TO BE
BY SNOW LEOPARD SOCIETY AT ITS SOLE DISCRETION, DEFAMATORY, OBSCENE,
PORNOGRAPHIC, INDECENT, ABUSIVE, OFFENSIVE, HARASSING, VIOLENT, HATEFUL,
RACIST, DISCRIMINATORY, INFLAMMATORY OR OTHERWISE OBJECTIONABLE OR
INAPPROPRIATE; AND, IN GENERAL, ACCESS, DOWNLOAD, UPLOAD, SHARE,
COMMUNICATE ANY CONTENT AND/OR USE THE SNOW LEOPARD SOCIETY WEBSITE
OR SNOW LEOPARD SOCIETY PROPERTY IN A WAY THAT MAY INFRINGE THE RIGHTS,
INCLUDING INTELLECTUAL PROPERTY RIGHTS, OF SNOW LEOPARD SOCIETY OR
THIRD PARTIES, DAMAGE THE REPUTATION, RIGHTS AND INTERESTS OF SNOW
LEOPARD SOCIETY, OR FALSELY SUGGEST AN AFFILIATION WITH OR ENDORSEMENT
BY SNOW LEOPARD SOCIETY.
(II) DECOMPILE, DISASSEMBLE THE SNOW LEOPARD SOCIETY WEBSITE, REVERSE
ENGINEER OR ATTEMPT TO DISCOVER OR RECONSTRUCT THE SOURCE CODE, THE
IDEAS ON WHICH IT IS BASED, THE ALGORITHMS, THE FILE FORMATS OR THE
PROGRAMMING OR INTEROPERABILITY INTERFACES OF THE SNOW LEOPARD
SOCIETY WEBSITE EXCEPT TO THE EXTENT PERMITTED BY LAW, IN ANY MANNER
WHATSOEVER. IN THE EVENT THE USER WISHES TO OBTAIN THE INFORMATION

NECESSARY TO IMPLEMENT THE INTEROPERABILITY OF SNOW LEOPARD SOCIETY
THE WEBSITE WITH OTHER SOFTWARE DEVELOPED OR INDEPENDENTLY ACQUIRED
BY THE USER, FOR USE IN ACCORDANCE WITH THE DESTINATION OF THE SNOW
LEOPARD SOCIETY WEBSITE, THE USER UNDERTAKES, BEFORE RELYING ON A THIRD
PARTY, TO FIRST CONSULT SNOW LEOPARD SOCIETY WHICH MAY PROVIDE THE
NECESSARY INFORMATION FOR THE IMPLEMENTATION OF SUCH INTEROPERABILITY.
THE USER ACKNOWLEDGE THAT, WHERE APPROPRIATE, THE EXACT COST
INCURRED INTERNALLY BY SNOW LEOPARD SOCIETY FOR PROVIDING THIS
INFORMATION WILL BE INVOICED BY SNOW LEOPARD SOCIETY TO THE USER;
(III) PROCEED ALONE, OR WITH HELP OF A THIRD-PARTY SERVICE PROVIDER, TO
CORRECT OF ANY ERRORS IN AND/OR ALTER ANY CONTENT OF THE SNOW LEOPARD
SOCIETY WEBSITE IN ORDER TO MAKE IT CONFORM TO HER/HIS OWN PURPOSES
(SNOW LEOPARD SOCIETY ALONE RESERVES FOR ITSELF THE EXERCISE OF THIS
RIGHT IN ACCORDANCE WITH EXCEPTIONS PROVIDED BY LAW); OR INTEGRATE OR
COMBINE THE SNOW LEOPARD SOCIETY WEBSITE WITH OTHER SOFTWARE OR
DOCUMENTS OR CREATE COMPOSITE OR DERIVATIVE WORKS WITH HELP OF ALL OR
PARTS OF THE SNOW LEOPARD SOCIETY WEBSITE;
AND, IN GENERAL, VIOLATE ANY LAW OR REGULATION, OR MAKE ANY USE OF THE
SNOW LEOPARD SOCIETY WEBSITE, SERVICES OR SNOW LEOPARD SOCIETY
PROPERTY THAT MAY BE DEEMED CONTRARY TO PUBLIC ORDER OR UNFAIR.


<h2 sx={{
      fontSize: { xs: "medium", md: "1.4rem" },
      color: theme == "white" ? "black" : "white",
      fontWeight: "bold",
      textAlign: "center",
    }}>
5.2 UNDERTAKINGS OF SNOW LEOPARD SOCIETY
</h2>

SNOW LEOPARD SOCIETY ENDEAVORS USE REASONABLE EFFORTS TO (I) ACT
HONESTLY, FAIRLY AND PROFESSIONALLY, (II) COMMUNICATE WITH THE HOLDERS
OF SNOW LEOPARD SOCIETY NFT IN A FAIR AND CLEAR MANNER, (III) PREVENT,
IDENTIFY, MANAGE AND DISCLOSE ANY CONFLICTS OF INTEREST THAT MAY ARISE,
(IV) MAINTAIN ALL OF ITS SYSTEMS AND SECURITY ACCESS PROTOCOLS TO
APPROPRIATE STANDARDS OF APPLICABLE LAWS AND REGULATIONS, AND, IN
GENERAL (V) ACT IN THE BEST INTERESTS OF THE HOLDERS OF SNOW LEOPARD
SOCIETY NFT AND TREAT THEM EQUALLY, UNLESS PROVIDED OTHERWISE ON THE
SNOW LEOPARD SOCIETY WEBSITE OR ANY OTHER NOTICE BY SNOW LEOPARD
SOCIETY.

<h1 sx={{
      fontSize: { xs: "medium", md: "1.4rem" },
      color: theme == "white" ? "black" : "white",
      fontWeight: "bold",
      textAlign: "center",
    }}>
6. SECURITY
</h1>

<h2 sx={{
      fontSize: { xs: "medium", md: "1.4rem" },
      color: theme == "white" ? "black" : "white",
      fontWeight: "bold",
      textAlign: "center",
    }}>
6.1 SNOW LEOPARD SOCIETY WEBSITE SECURITY
</h2>

SNOW LEOPARD SOCIETY SHALL MAKE ITS BEST EFFORTS TO DEPLOY THE
NECESSARY RESOURCES TO ENSURE USERS’ ACCESS TO AND EFFECTIVE
OPERATION OF THE SNOW LEOPARD SOCIETY WEBSITE TWENTY-FOUR HOURS A
DAY AND SEVEN DAYS A WEEK. HOWEVER, GIVEN THE LIMITATIONS RELATED TO THE
INTERNET, SNOW LEOPARD SOCIETY CANNOT GUARANTEE THAT ACCESS AND
OPERATION OF THE SNOW LEOPARD SOCIETY WEBSITE WILL NOT BE INTERRUPTED,
SUCH AS IN EVENT OF FORCE MAJEURE, MALFUNCTION OF THE USERS’ EQUIPMENT,
MALFUNCTIONS OF THE USERS’ INTERNET NETWORKS AND/OR MAINTENANCE
OPERATIONS DESIGNED TO IMPROVE THE SNOW LEOPARD SOCIETY WEBSITE.

THE USER HEREBY REPRESENTS, WARRANTS, AND AGREES THAT, WHEN
ACCESSING AND/OR USING THE SNOW LEOPARD SOCIETY WEBSITE AND SERVICES,
THE USER SHALL REFRAIN FROM ANY ACT AND/OR OMISSION WHICH COULD, IN ANY
WAY WHATSOEVER (I) JEOPARDIZE THE SECURITY OF THE SNOW LEOPARD SOCIETY
WEBSITE; (II) ATTEMPT, IN ANY MANNER, TO OBTAIN PASSWORDS OR OTHER
SECURITY INFORMATION FROM ANY OTHER USER; (III) VIOLATE THE SECURITY OF
ANY COMPUTER NETWORK, OR CRACKS ANY PASSWORDS OR SECURITY
ENCRYPTION CODES; (IV) RUN ANY PROCESSES THAT INTERFERE WITH THE PROPER
WORKING OF THE SNOW LEOPARD SOCIETY WEBSITE AND SERVICES; (V) DISTURB,
HINDER AND/OR PREVENT THE PROPER FUNCTIONING OF THE SNOW LEOPARD
SOCIETY WEBSITE AND SERVICES (SUCH AS, BUT NOT LIMITED TO, DOWNLOADING
VIRUSES OR MALICIOUS CODE WHATSOEVER OR BY PERFORMING HACKING
ACTIVITIES OF ANY NATURE OR THAT OTHERWISE INTERFERE WITH THE PROPER
FUNCTIONING OF THE SNOW LEOPARD SOCIETY WEBSITE AND SERVICES).


<h2 sx={{
      fontSize: { xs: "medium", md: "1.4rem" },
      color: theme == "white" ? "black" : "white",
      fontWeight: "bold",
      textAlign: "center",
    }}>
6.2 MALICIOUS THIRD PARTIES
</h2>

PLEASE BE AWARE THAT MALICIOUS THIRD PARTIES MAY OFFER FOR SALE NFT
COUNTERFEITED SNOW LEOPARD SOCIETY PROPERTY AND/OR FALSELY ACT AS
AFFILIATED TO OR ENDORSED BY SNOW LEOPARD SOCIETY. IN CASE OF DOUBT,
PLEASE CONTACT SNOW LEOPARD SOCIETY IN ACCORDANCE WITH ARTICLE 12
BELOW.

YOUR INTERACTIONS WITH THESE THIRD PARTIES ARE AT YOUR OWN RISKS AND
DISCRETION. SNOW LEOPARD SOCIETY IS NOT RESPONSIBLE, IN ANY WAY
WHATSOEVER, FOR ANY ACT OR OMISSION OF SAID MALICIOUS THIRD PARTIES, NOR
ANY ADVERSE CONSEQUENCE RESULTING FROM YOUR INTERACTIONS WITH THEM.


<h1 sx={{
      fontSize: { xs: "medium", md: "1.4rem" },
      color: theme == "white" ? "black" : "white",
      fontWeight: "bold",
      textAlign: "center",
    }}>
7. DISCLAIMER
</h1>

SNOW LEOPARD SOCIETY OFFERS SERVICES RELATED TO CRYPTO-ASSETS (NFT)
THAT ARE UNIQUE AND NOT FUNGIBLE WITH OTHER CRYPTO-ASSETS. EACH SNOW
LEOPARD SOCIETY NFT IS UNIQUE AND EXCLUSIVE TO ITS OWNER.

SNOW LEOPARD SOCIETY IS NOT A PROVIDER OF DIGITAL ASSET SERVICES
INCLUDING, BUT NOT LIMITED TO, SERVICES REGARDING INITIAL COIN OFFERING;
CUSTODY OF DIGITAL ASSETS ON BEHALF OF THIRD PARTIES OR ACCESS TO DIGITAL
ASSETS FOR THE PURPOSE OF HOLDING, STORING AND TRANSFERRING DIGITAL
ASSETS; THE PURCHASE AND SALE OF DIGITAL ASSETS IN LEGAL TENDER; THE
EXCHANGE OF DIGITAL ASSETS FOR OTHER DIGITAL ASSETS; THE OPERATION OF A
DIGITAL ASSET TRADING PLATFORM; OR ANY SERVICES RELATED TO THIRD PARTY
ORDER RECEPTION AND TRANSMISSION, THIRD PARTY PORTFOLIO MANAGEMENT,
ADVICE, UNDERWRITING, GUARANTEED PLACEMENT AND UNGUARANTEED
PLACEMENT.

SNOW LEOPARD SOCIETY DOES NOT PROVIDE ASSET INTERMEDIATION SERVICES
INCLUDING, BUT NOT LIMITED TO, SERVICES RELATED TO THE OFFER, TO CLIENTS
OR POTENTIAL CLIENTS, TO ACQUIRE RIGHTS ON ONE OR MORE ASSETS ON THE
BASIS OF THE POSSIBILITY OF A DIRECT OR INDIRECT FINANCIAL RETURN OR
SIMILAR ECONOMIC EFFECT.

IN THIS REGARD, THE USER HEREBY REPRESENTS, WARRANTS, AND AGREES THAT
ANY USE OF THE SNOW LEOPARD SOCIETY WEBSITE AND SERVICES, INCLUDING ANY
PURCHASE OF A SNOW LEOPARD SOCIETY NFT, IS MADE FOR ITS SOLE PERSONAL
COLLECTION, USE AND ENJOYMENT. USER SHALL REFRAIN FROM ANY ACT AND/OR
OMISSION WHICH COULD, IN ANY WAY WHATSOEVER, BE INTERPRETED AS OR
SUGGEST THAT (I) THE USER IS ACCESSING OR USING THE SNOW LEOPARD SOCIETY
WEBSITE AND/OR SERVICES, INCLUDING PURCHASING A SNOW LEOPARD SOCIETY
NFT, FOR SPECULATIVE OR INVESTMENT PURPOSES, FOR USE AS A SUBSTITUTE
FOR CURRENCY OR OTHER MEDIUM OF EXCHANGE, OR FOR RESALE OR
REDISTRIBUTION, OR THAT (II) ACCESSING OR USING THE SNOW LEOPARD SOCIETY

WEBSITE AND/OR SERVICES, INCLUDING PURCHASING A SNOW LEOPARD SOCIETY
NFT, MAY CONSTITUTE AN OPPORTUNITY TO GAIN ECONOMIC BENEFIT OR PROFIT,
OR AN INVESTMENT, EQUITY, OR OTHER OWNERSHIP OR PROFIT-SHARING INTEREST
IN SNOW LEOPARD SOCIETY OR ITS AFFILIATES OR BUSINESS PARTNERS OF ANY
KIND. IN THIS REGARD, SNOW LEOPARD SOCIETY MAKES NO WARRANTIES
WHATSOEVER WITH REGARD TO ANY FUTURE VALUE OR RESALE PRICE OF A SNOW
LEOPARD SOCIETY NFT.

YOU ARE THE SOLE RESPONSIBLE FOR YOUR COMPLIANCE WITH APPLICABLE LAWS
AND REGULATIONS, INCLUDING TAX OBLIGATIONS IN RELATION WITH NFT AND
CRYPTOCURRENCIES. PLEASE BE AWARE THAT CHANGES IN APPLICABLE LAWS AND
REGULATIONS MAY IMPACT THE SERVICES AND YOUR RIGHTS AND OBLIGATIONS
REGARDING YOUR SNOW LEOPARD SOCIETY NFT.



<h1 sx={{
      fontSize: { xs: "medium", md: "1.4rem" },
      color: theme == "white" ? "black" : "white",
      fontWeight: "bold",
      textAlign: "center",
    }}>
8. WARRANTY AND LIABILITY
</h1>

<h2 sx={{
      fontSize: { xs: "medium", md: "1.4rem" },
      color: theme == "white" ? "black" : "white",
      fontWeight: "bold",
      textAlign: "center",
    }}>
8.1 WARRANTIES
</h2>

IT IS EXPRESSLY AGREED THAT SNOW LEOPARD SOCIETY OBLIGATIONS UNDER
THESE TERMS ARE OBLIGATIONS OF MEANS. TO THE GREATEST EXTENT PERMITTED
BY APPLICABLE LAW, THE USER EXPRESSLY ACKNOWLEDGES THAT THE SNOW
LEOPARD SOCIETY WEBSITE, SERVICES, INCLUDING SNOW LEOPARD SOCIETY NFT,
ARE PROVIDED BY SNOW LEOPARD SOCIETY “AS IS”. OTHER THAN AS PROVIDED IN
THESE TERMS AND TO THE FULLEST EXTENT PERMISSIBLE BY APPLICABLE LAW,
SNOW LEOPARD SOCIETY MAKES NO OTHER WARRANTIES OR REPRESENTATIONS,
EXPRESS OR IMPLIED, AND HEREBY DISCLAIMS ALL IMPLIED WARRANTIES.

SNOW LEOPARD SOCIETY MAKES NO WARRANTIES WHATSOEVER, REGARDING THE
SNOW LEOPARD SOCIETY WEBSITE, THE SERVICES, AND ANY TRANSACTION
INVOLVING, IN WHOLE OR IN PART, SNOW LEOPARD SOCIETY NFT AND/OR
CRYPTOCURRENCIES, INCLUDING, BUT NOT LIMITED TO, WITH REGARD TO ANY RISK
ASSOCIATED WITH SNOW LEOPARD SOCIETY NFT, SUCH AS, RISK OF FAILURE TO
TRANSFER THE NFT TO THE USER DUE TO AN ERROR, SUCH AS FORGOTTEN
PASSWORDS, MISTYPED ADDRESSES OR INCORRECTLY CONSTRUCTED
TRANSACTIONS, MINING ATTACKS, CYBERSECURITY ATTACKS, BLOCKCHAIN
MALFUNCTIONS OR OTHER TECHNICAL ERRORS, TELECOMMUNICATIONS FAILURE,
UNFAVORABLE REGULATORY DETERMINATIONS OR ACTIONS IN ONE OR MORE
JURISDICTIONS (INCLUDING WITH RESPECT TO NFTS AND/OR CRYPTOCURRENCIES),

TAXATION OF NFTS OR CRYPTOCURRENCIES, PERSONAL INFORMATION
DISCLOSURE, UNINSURED LOSSES, UNANTICIPATED RISKS, VOLATILITY RISKS,
SERVER FAILURE OR DATA LOSS, CORRUPTED OR OTHERWISE INACCESSIBLE
DIGITAL WALLETS, UNAUTHORIZED ACCESS, INABILITY TO ACCESS, TRANSFER OR
DISPLAY THE NFT, RISKS ARISING FROM THIRD-PARTY PROVIDERS, INCLUDING
THIRD-PARTY PROVIDERS THAT MAY MINT AND/OR STORE THE NFT, AND ANY
DAMAGES ARISING FROM ANY UNAUTHORIZED THIRD-PARTY ACTIVITIES, INCLUDING
WITHOUT LIMITATION THE INTRODUCTION OF VIRUSES OR OTHER MALICIOUS CODE,
PHISHING ATTACKS, SYBIL ATTACKS, FIFTY-ONE PERCENT (51%) ATTACKS, BRUTE
FORCING CHANGES TO THE PROTOCOL RULES OF THE BLOCKCHAIN (I.E., “FORKS”),
OR OTHER MEANS OF ATTACK THAT MAY AFFECT, IN ANY WAY, THE NFT.

SNOW LEOPARD SOCIETY DOES NOT WARRANT THAT THE USER’S ACCESS AND USE
OF SNOW LEOPARD SOCIETY WEBSITE AND THE SERVICES WILL BE
UNINTERRUPTED, TIMELY AND FREE FROM ERRORS, MALFUNCTIONS, VIRUSES AND
MALICIOUS CODES OF ANY KIND WHATSOEVER. NO INFORMATION PROVIDED ON THE
SNOW LEOPARD SOCIETY WEBSITE IS EVER GUARANTEED IN ANY WAY
WHATSOEVER.

THE USER EXPRESSLY ACKNOWLEDGES AND ACCEPTS THAT ELECTRONIC
COMMUNICATIONS MAY NOT BE FREE FROM INTERFERENCES WITH THIRD PARTIES.
SNOW LEOPARD SOCIETY SHALL IN NO EVENT BE LIABLE FOR ANY DAMAGES,
LOSSES, COSTS, EXPENSES AND LOSS OF PROFIT, OF WHATEVER NATURE AND KIND,
RESULTING FROM OR ARISING OUT OF SUCH INTERFERENCE WITH THIRD PARTIES
THROUGH THE INTERNET NETWORK.



<h2 sx={{
      fontSize: { xs: "medium", md: "1.4rem" },
      color: theme == "white" ? "black" : "white",
      fontWeight: "bold",
      textAlign: "center",
    }}>
8.2 INDEMNIFICATION
</h2>

THE USER SHALL INDEMNIFY, DEFEND AND HOLD SNOW LEOPARD SOCIETY, AND ITS
MEMBER, DIRECTORS, OFFICERS, EMPLOYEES, AND AGENTS (COLLECTIVELY, &quot;THE
SNOW LEOPARD SOCIETY CLAIMANTS&quot;) HARMLESS FROM AND AGAINST ANY AND ALL
CLAIMS, LIABILITIES, JUDGMENTS, AWARDS, LOSSES, DAMAGES, COSTS AND
EXPENSES (INCLUDING, BUT NOT LIMITED TO, REASONABLE ATTORNEYS&#39; FEES),
ARISING OUT FROM (I) ANY BREACH BY THE USER, OR ANY OF ITS RESPECTIVE
EMPLOYEES OR AGENTS IF ANY, OF THIS TERMS OR OF ANY WARRANTY,
REPRESENTATION, COVENANT OR OBLIGATION CONTAINED HEREIN; (II) ANY
INFRINGEMENT OR ALLEGED INFRINGEMENT ON THE PART OF THE SNOW LEOPARD
SOCIETY CLAIMANTS IN CONNECTION WITH ANY AND ALL USE OF THE SNOW

LEOPARD SOCIETY WEBSITE, SERVICES AND/OR SNOW LEOPARD SOCIETY NFT BY
THE USER.



<h2 sx={{
      fontSize: { xs: "medium", md: "1.4rem" },
      color: theme == "white" ? "black" : "white",
      fontWeight: "bold",
      textAlign: "center",
    }}>
8.3 LIMITATION OF LIABILITY
</h2>
TO THE GREATEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL
SNOW LEOPARD SOCIETY BE LIABLE FOR ANY INDIRECT DAMAGES CAUSED TO A
USER IN RELATION TO ACCESS AND/OR USE OF THE SNOW LEOPARD SOCIETY
WEBSITE AND/OR THE SERVICES.



<h1 sx={{
      fontSize: { xs: "medium", md: "1.4rem" },
      color: theme == "white" ? "black" : "white",
      fontWeight: "bold",
      textAlign: "center",
    }}>
9. MISCELLANEOUS
</h1>

<h2 sx={{
      fontSize: { xs: "medium", md: "1.4rem" },
      color: theme == "white" ? "black" : "white",
      fontWeight: "bold",
      textAlign: "center",
    }}>
9.1 BREACH OF TERMS
</h2>
IF THE USER’S UTILIZATION OF THE SNOW LEOPARD SOCIETY WEBSITE IS DEEMED IN
BREACH OF THE TERMS, SNOW LEOPARD SOCIETY RESERVES THE RIGHT TO LIMIT,
SUSPEND OR TERMINATE, TEMPORARILY OR PERMANENTLY, AS OF RIGHT, WITHOUT
ANY INDEMNIFICATION, COMPENSATION OR REFUND WHATSOEVER BEING OWED
AND WITHOUT ANY PREJUDICE TO ANY LEGAL ACTION THAT SNOW LEOPARD
SOCIETY MAY BE ENTITLED TO, THE USER’S ACCESS TO THE SNOW LEOPARD
SOCIETY WEBSITE AND/OR THE SERVICES AVAILABLE TO THE USER. SNOW LEOPARD
SOCIETY SHALL INFORM THE USER OF ITS DECISION TO SUSPEND OR LIMIT THE
USER’S RIGHTS AND MAY, AT ITS DISCRETION, DECIDE TO RESTORE THE USER’S
RIGHTS.

<h2 sx={{
      fontSize: { xs: "medium", md: "1.4rem" },
      color: theme == "white" ? "black" : "white",
      fontWeight: "bold",
      textAlign: "center",
    }}>
9.2 THIRD PARTY CONTENT
</h2>
THE SNOW LEOPARD SOCIETY WEBSITE MAY DISPLAY HYPERTEXT LINKS
REDIRECTING THE USER TO THIRD PARTY WEBSITES AND/OR APPLICATIONS. SNOW
LEOPARD SOCIETY SHALL NOT BE HELD LIABLE, IN ANY WAY WHATSOEVER, IN
RESPECT OF ANY HYPERTEXT LINKS TO THIRD PARTIES THAT MAY BE ACCESSIBLE
ON THE SNOW LEOPARD SOCIETY WEBSITE. IN THIS RESPECT, PLEASE NOTE THAT
SNOW LEOPARD SOCIETY NEITHER HAS ANY CONTROL OVER THE CONTENT
PUBLISHED BY SUCH THIRD PARTIES NOR MONITORS SUCH CONTENT. AS A RESULT,
SNOW LEOPARD SOCIETY SHALL IN NO EVENT BE HELD LIABLE IN RESPECT OF ANY
CONTENT PUBLISHED BY THIRD PARTIES WHATSOEVER. THE USER IS HEREBY

INVITED TO DULY READ THE TERMS AND CONDITIONS GOVERNING THIRD-PARTY
WEBSITES AND APPLICATIONS THAT THE USER MAY ACCESS BY CLICKING ON
HYPERTEXT LINKS DISPLAYED ON THE SNOW LEOPARD SOCIETY WEBSITE AND
RELATED WEBSITE PAGES.

IN THE EVENT THAT ANY CONTENT POSTED ON THE SNOW LEOPARD SOCIETY
WEBSITE DOES NOT COMPLY WITH THESE TERMS AND/OR INFRINGES APPLICABLE
LEGAL AND REGULATORY PROVISIONS, IN PARTICULAR BECAUSE IT CONSTITUTES
MANIFESTLY UNLAWFUL CONTENT (E.G., DEFAMATORY, DENIGRATING OR
INFRINGING ON THE USER&#39;S INTELLECTUAL PROPERTY RIGHTS), ANY USER MAY
REPORT SUCH INFRINGEMENT BY CONTACTING SNOW LEOPARD SOCIETY IN
ACCORDANCE WITH ARTICLE 12.


<h2 sx={{
      fontSize: { xs: "medium", md: "1.4rem" },
      color: theme == "white" ? "black" : "white",
      fontWeight: "bold",
      textAlign: "center",
    }}>
9.3 ASSIGNMENT
</h2>
SNOW LEOPARD SOCIETY MAY TRANSFER ALL OR PART OF ITS RIGHTS AND
OBLIGATIONS UNDER THESE TERMS TO ANY ENTITY, AFFILIATE, SUBSIDIARY OR
THIRD-PARTY, INCLUDING, BUT NOT LIMITED TO, IN CASE OF MERGER, DIVISION,
PARTIAL ASSET TRANSFER OR FULL OR PARTIAL BUSINESS DISPOSAL. THE USER
SHALL NOT TRANSFER ALL OR PART OF ITS OBLIGATIONS UNDER THESE TERMS, IN
ANY WAY WHATSOEVER, WITHOUT THE EXPRESS PRIOR WRITTEN AGREEMENT OF
METASIMBLA LLC OR SNOW LEOPARD SOCIETY.
<h2 sx={{
      fontSize: { xs: "medium", md: "1.4rem" },
      color: theme == "white" ? "black" : "white",
      fontWeight: "bold",
      textAlign: "center",
    }}>
9.4 VALIDITY
</h2>
IN THE EVENT ANY ONE OR MORE OF THE PROVISIONS OF THESE TERMS ARE
UNENFORCEABLE, IT SHALL BE STRICKEN FROM THE APPLICABLE DOCUMENT, BUT
THE REMAINDER OF THE TERMS SHALL REMAIN IN FORCE. THE PROVISIONS
DECLARED UNENFORCEABLE SHALL BE REPLACED BY THE PROVISIONS THAT ARE
CLOSEST IN MEANING AND SCOPE TO THE INITIAL PROVISIONS.
<h2 sx={{
      fontSize: { xs: "medium", md: "1.4rem" },
      color: theme == "white" ? "black" : "white",
      fontWeight: "bold",
      textAlign: "center",
    }}>
9.5 ELECTRONIC COMMUNICATION
</h2>
IN ACCORDANCE WITH APPLICABLE LAW, THE USER ACKNOWLEDGES AND AGREES
THAT INFORMATION EXCHANGED BETWEEN THE USER AND SNOW LEOPARD
SOCIETY IN ELECTRONIC FORMAT (INCLUDING VIA EMAIL) SHALL BE DEEMED VALID
MEANS OF COMMUNICATION., NOTICE AND PROOF, EQUIVALENT TO INFORMATION IN
PAPER FORMAT.


<h1 sx={{
      fontSize: { xs: "medium", md: "1.4rem" },
      color: theme == "white" ? "black" : "white",
      fontWeight: "bold",
      textAlign: "center",
    }}>
10. APPLICABLE LAW
</h1>
THE VALIDITY OF THESE TERMS AND ANY OF ITS TERMS AND PROVISIONS, AS WELL
AS THE RIGHTS AND DUTIES OF THE PARTIES HEREUNDER, SHALL BE GOVERNED,
INTERPRETED AND ENFORCED IN ACCORDANCE WITH THE FEDERAL LAW OF THE
UNITED STATES AND THE LAW OF THE STATE OF PENNSYLVANIA.

IN THE EVENT OF A DISPUTE ARISING BETWEEN THE PARTIES REGARDING THE
INTERPRETATION, EXECUTION OR TERMINATION OF THESE TERMS, THE PARTIES
SHALL ENDEAVOR TO RESOLVE SUCH ISSUE THROUGH AMICABLE MEANS.
NOTWITHSTANDING ANYTHING TO THE CONTRARY PROVIDED HEREIN, THE STATE OR
FEDERAL COURT OF APPROPRIATE JURISDICTION LOCATED IN KENT COUNTY,
PENNSYLVANIA SHALL BE THE VENUE FOR ANY FORMAL DISPUTES BETWEEN USER
AND SNOW LEOPARD SOCIETY.

<h1 sx={{
      fontSize: { xs: "medium", md: "1.4rem" },
      color: theme == "white" ? "black" : "white",
      fontWeight: "bold",
      textAlign: "center",
    }}>
11. CONTACT INFORMATION
</h1>
PLEASE CONTACT US BY E-MAIL AT [ADMIN@METASIMBA.IO]

<h1 sx={{
      fontSize: { xs: "medium", md: "1.4rem" },
      color: theme == "white" ? "black" : "white",
      fontWeight: "bold",
      textAlign: "center",
    }}>
12. DIGITAL MILLENNIUM COPYRIGHT ACT
</h1>

NOTICE. WE RESPECT THE INTELLECTUAL PROPERTY RIGHTS OF OTHERS AND WE
ASK YOU TO DO THE SAME. IF YOU ARE A COPYRIGHT OWNER OR AN AGENT OF A
COPYRIGHT OWNER AND BELIEVE THAT ANY CONTENT ON THE SERVICES INFRINGES
UPON YOUR COPYRIGHTS (OTHER THAN CONTENT THAT WAS PREVIOUSLY
UPLOADED BY YOU TO SNOW LEOPARD SOCIETY AND AS TO WHICH THE USER-TO-
USER COMPLAINT PROCESS APPLIES AS DESCRIBED BELOW), YOU MAY SUBMIT A
NOTIFICATION PURSUANT TO THE DIGITAL MILLENNIUM COPYRIGHT ACT (&quot;DMCA&quot;) BY
CONTACTING OUR COPYRIGHT AGENT AT [EMAIL PROTECTED] OR TO THE ADDRESS
PROVIDED IN ARTICLE 12, ATTENTION DMCA AGENT. IF A COPYRIGHT OWNER IS
UNDER THE AGE OF 13, A DMCA NOTICE MUST BE SUBMITTED BY A PARENT OR
OTHER REPRESENTATIVE OF THE RIGHTSHOLDER, RATHER THAN DIRECTLY BY AN

UNDER-13 USER. YOU ACKNOWLEDGE THAT IF YOU FAIL TO COMPLY WITH ALL OF
THE REQUIREMENTS OF THIS SECTION 5(A), YOUR DMCA NOTICE MAY NOT BE VALID.
YOU MUST PROVIDE THE FOLLOWING INFORMATION IN WRITING (SEE 17 U.S.C
512(C)(3) FOR FURTHER DETAIL):

AN ELECTRONIC OR PHYSICAL SIGNATURE OF THE PERSON AUTHORIZED TO ACT ON
BEHALF OF THE OWNER OF THE COPYRIGHT OR OTHER RIGHT BEING INFRINGED;
A DESCRIPTION OF THE COPYRIGHT-PROTECTED WORK OR OTHER INTELLECTUAL
PROPERTY RIGHT THAT YOU CLAIM HAS BEEN INFRINGED;
A DESCRIPTION OF THE MATERIAL THAT YOU CLAIM IS INFRINGING AND WHERE IT IS
LOCATED;
YOUR ADDRESS, TELEPHONE NUMBER, AND EMAIL ADDRESS;
A STATEMENT BY YOU THAT YOU HAVE A GOOD FAITH BELIEF THAT THE USE OF
THOSE MATERIALS IS NOT AUTHORIZED BY THE COPYRIGHT OWNER, ITS AGENT, OR
THE LAW; AND
A STATEMENT BY YOU THAT THE ABOVE INFORMATION IN YOUR NOTICE IS
ACCURATE AND THAT, UNDER PENALTY OF PERJURY, YOU ARE THE COPYRIGHT OR
INTELLECTUAL PROPERTY OWNER OR AUTHORIZED TO ACT ON THE COPYRIGHT OR
INTELLECTUAL PROPERTY OWNER’S BEHALF.
COUNTER-NOTICE. REGARDING ANY CONTENT THAT WAS REMOVED OR DISABLED, IF
YOU BELIEVE THAT YOUR CONTENT IS NOT INFRINGING OR THAT YOU HAVE THE
AUTHORIZATION FROM THE COPYRIGHT OWNER, THE COPYRIGHT OWNER’S AGENT,
OR PURSUANT TO THE LAW, TO POST AND USE THE MATERIAL IN YOUR CONTENT,
YOU MAY SEND A COUNTER-NOTICE TO OUR COPYRIGHT AGENT. ANY COUNTER-
NOTICE SUBMITTED ON BEHALF OF AN UNDER-13 USER MUST BE SUBMITTED BY A
PARENT OR OTHER ADULT REPRESENTATIVE. WHEN OUR COPYRIGHT AGENT
RECEIVES A COUNTER-NOTICE, WE MAY SEND A COPY OF THE COUNTER-NOTICE TO
THE ORIGINAL COMPLAINING PARTY INFORMING THAT PARTY THAT WE MAY, IN 10
BUSINESS DAYS, REPLACE THE REMOVED CONTENT OR STOP DISABLING IT. UNLESS
THE COPYRIGHT OWNER FILES AN ACTION SEEKING A COURT ORDER AGAINST THE
PROVIDER OF THE CONTENT, THE REMOVED CONTENT MAY BE REPLACED OR
ACCESS TO IT RESTORED, IN 10 TO 14 BUSINESS DAYS OR MORE AFTER RECEIPT OF
THE COUNTER-NOTICE, IN METASIMBA LLC OR SNOW LEOPARD SOCIETY SOLE
DISCRETION.

REPEAT INFRINGER POLICY. SNOW LEOPARD SOCIETYS’ INTELLECTUAL PROPERTY
POLICY IS TO: (I) REMOVE OR DISABLE ACCESS TO MATERIAL THAT SNOW LEOPARD
SOCIETY KNOWS TO BE INFRINGING THE INTELLECTUAL PROPERTY RIGHTS OF
THIRD PARTIES OR THAT HAS BEEN IDENTIFIED IN A VALID DMCA NOTICE SUBMITTED
BY AN INTELLECTUAL PROPERTY RIGHTS OWNER OR HIS OR HER AGENT; AND (II) IN
APPROPRIATE CIRCUMSTANCES, TO TERMINATE THE ACCOUNT OF AND BLOCK
ACCESS TO THE SNOW LEOPARD SOCIETY WEBSITE AND SERVICES BY ANY USER
WHO REPEATEDLY OR EGREGIOUSLY INFRINGES OTHER PEOPLE’S COPYRIGHTS OR
OTHER INTELLECTUAL PROPERTY RIGHTS.

TRADEMARK INFRINGEMENT OUR POLICIES PROHIBIT A USER FROM PROVIDING
USER-GENERATED CONTENT THAT INFRINGES TRADEMARKS. IF A USER PROVIDES
CONTENT THAT INFRINGES TRADEMARKS, THE USER’S CONTENT CAN BE BLOCKED
OR REMOVED.

IF YOU ARE A TRADEMARK OWNER THAT BELIEVES YOUR TRADEMARK IS BEING
INFRINGED, PLEASE NOTE THAT WE ARE NOT IN A POSITION TO MEDIATE DISPUTES
BETWEEN USERS AND THE HOLDERS OF TRADEMARK RIGHTS. THAT BEING SAID, WE
TAKE YOUR RIGHTS SERIOUSLY. SO, WE WILL LOOK INTO AND TRY TO RESOLVE ANY
ALLEGATIONS OF TRADEMARK INFRINGEMENT. THEREFORE, IF YOU FEEL THAT YOUR
TRADEMARK RIGHTS ARE BEING INFRINGED, CONTACT OUR TRADEMARK AGENT AT
[EMAIL PROTECTED] OR AT THE ADDRESS PROVIDED IN ARTICLE 12, ATTENTION
TRADEMARK AGENT. WHEN YOU CONTACT US, PLEASE PROVIDE THE FOLLOWING
INFORMATION IN WRITING:

AN ELECTRONIC OR PHYSICAL SIGNATURE OF THE PERSON AUTHORIZED TO ACT ON
BEHALF OF THE OWNER OF THE TRADEMARK;
A DESCRIPTION OF THE TRADEMARK RIGHT THAT YOU CLAIM HAS BEEN INFRINGED;
A DESCRIPTION OF THE MATERIAL THAT YOU CLAIM IS INFRINGING AND WHERE IT IS
LOCATED;
YOUR ADDRESS, TELEPHONE NUMBER, AND EMAIL ADDRESS;
A STATEMENT BY YOU THAT YOU HAVE A GOOD FAITH BELIEF THAT THE USE OF
THOSE MATERIALS IS NOT AUTHORIZED BY THE TRADEMARK OWNER, ITS AGENT, OR
THE LAW; AND

A STATEMENT BY YOU THAT THE ABOVE INFORMATION IN YOUR NOTICE IS
ACCURATE AND THAT, UNDER PENALTY OF PERJURY, YOU ARE THE TRADEMARK
OWNER OR AUTHORIZED TO ACT ON THE COPYRIGHT OR INTELLECTUAL PROPERTY
OWNER’S BEHALF.
{/* <h2 sx={{
      fontSize: { xs: "medium", md: "1.4rem" },
      color: theme == "white" ? "black" : "white",
      fontWeight: "bold",
      textAlign: "center",
    }}>
8.1 WARRANTIES
</h2> */}
        </Typography>

        <Box style={{height:"100px"}}>

        </Box>
      </Box>
    </Box>
  );
}
